// <auto-generated />
using GabsApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GabsApi.Migrations
{
    [DbContext(typeof(GabsContext))]
    partial class GabsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GabsApi.Model.Gabs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gabss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 29,
                            Description = "Gabs is nice!",
                            Name = "Gabs"
                        });
                });

            modelBuilder.Entity("GabsApi.Model.OtherGabs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GabsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GabsId");

                    b.ToTable("OtherGabss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Description = "There's a lot of Gabs",
                            GabsId = 1,
                            Name = "Gabs"
                        });
                });

            modelBuilder.Entity("GabsApi.Model.OtherGabs", b =>
                {
                    b.HasOne("GabsApi.Model.Gabs", "Gabs")
                        .WithMany("GabsList")
                        .HasForeignKey("GabsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gabs");
                });

            modelBuilder.Entity("GabsApi.Model.Gabs", b =>
                {
                    b.Navigation("GabsList");
                });
#pragma warning restore 612, 618
        }
    }
}
